version: 2

sources:
  - name: northwind_raw
    schema: northwind_dbt
    
    tables:
      - name: dim_categories
      - name: dim_customers
      - name: dim_employee_territories
      - name: dim_employees
      - name: dim_order_details
      - name: dim_orders
      - name: dim_products
      - name: dim_region
      - name: dim_shippers
      - name: dim_suppliers
      - name: dim_territories
      - name: dim_us_states